// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: single_crawler.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CrawlerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timeout uint64 `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (x *CrawlerReq) Reset() {
	*x = CrawlerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_single_crawler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerReq) ProtoMessage() {}

func (x *CrawlerReq) ProtoReflect() protoreflect.Message {
	mi := &file_single_crawler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerReq.ProtoReflect.Descriptor instead.
func (*CrawlerReq) Descriptor() ([]byte, []int) {
	return file_single_crawler_proto_rawDescGZIP(), []int{0}
}

func (x *CrawlerReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlerReq) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type CrawlerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body     []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	HttpCode uint32 `protobuf:"varint,2,opt,name=http_code,json=httpCode,proto3" json:"http_code,omitempty"`
}

func (x *CrawlerResp) Reset() {
	*x = CrawlerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_single_crawler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrawlerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerResp) ProtoMessage() {}

func (x *CrawlerResp) ProtoReflect() protoreflect.Message {
	mi := &file_single_crawler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerResp.ProtoReflect.Descriptor instead.
func (*CrawlerResp) Descriptor() ([]byte, []int) {
	return file_single_crawler_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlerResp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CrawlerResp) GetHttpCode() uint32 {
	if x != nil {
		return x.HttpCode
	}
	return 0
}

var File_single_crawler_proto protoreflect.FileDescriptor

var file_single_crawler_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63,
	0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x0a, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x22, 0x3e, 0x0a, 0x0b, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x68, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x64, 0x65,
	0x32, 0x59, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x12, 0x48, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x72, 0x61, 0x77, 0x6c,
	0x65, 0x72, 0x12, 0x1a, 0x2e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63, 0x72, 0x61, 0x77,
	0x6c, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1b,
	0x2e, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x42, 0x12, 0x5a, 0x10, 0x2e,
	0x3b, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_single_crawler_proto_rawDescOnce sync.Once
	file_single_crawler_proto_rawDescData = file_single_crawler_proto_rawDesc
)

func file_single_crawler_proto_rawDescGZIP() []byte {
	file_single_crawler_proto_rawDescOnce.Do(func() {
		file_single_crawler_proto_rawDescData = protoimpl.X.CompressGZIP(file_single_crawler_proto_rawDescData)
	})
	return file_single_crawler_proto_rawDescData
}

var file_single_crawler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_single_crawler_proto_goTypes = []interface{}{
	(*CrawlerReq)(nil),  // 0: single_crawler.CrawlerReq
	(*CrawlerResp)(nil), // 1: single_crawler.CrawlerResp
}
var file_single_crawler_proto_depIdxs = []int32{
	0, // 0: single_crawler.SingleCrawler.SingleCrawler:input_type -> single_crawler.CrawlerReq
	1, // 1: single_crawler.SingleCrawler.SingleCrawler:output_type -> single_crawler.CrawlerResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_single_crawler_proto_init() }
func file_single_crawler_proto_init() {
	if File_single_crawler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_single_crawler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_single_crawler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrawlerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_single_crawler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_single_crawler_proto_goTypes,
		DependencyIndexes: file_single_crawler_proto_depIdxs,
		MessageInfos:      file_single_crawler_proto_msgTypes,
	}.Build()
	File_single_crawler_proto = out.File
	file_single_crawler_proto_rawDesc = nil
	file_single_crawler_proto_goTypes = nil
	file_single_crawler_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SingleCrawlerClient is the client API for SingleCrawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SingleCrawlerClient interface {
	SingleCrawler(ctx context.Context, in *CrawlerReq, opts ...grpc.CallOption) (*CrawlerResp, error)
}

type singleCrawlerClient struct {
	cc grpc.ClientConnInterface
}

func NewSingleCrawlerClient(cc grpc.ClientConnInterface) SingleCrawlerClient {
	return &singleCrawlerClient{cc}
}

func (c *singleCrawlerClient) SingleCrawler(ctx context.Context, in *CrawlerReq, opts ...grpc.CallOption) (*CrawlerResp, error) {
	out := new(CrawlerResp)
	err := c.cc.Invoke(ctx, "/single_crawler.SingleCrawler/SingleCrawler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SingleCrawlerServer is the server API for SingleCrawler service.
type SingleCrawlerServer interface {
	SingleCrawler(context.Context, *CrawlerReq) (*CrawlerResp, error)
}

// UnimplementedSingleCrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedSingleCrawlerServer struct {
}

func (*UnimplementedSingleCrawlerServer) SingleCrawler(context.Context, *CrawlerReq) (*CrawlerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SingleCrawler not implemented")
}

func RegisterSingleCrawlerServer(s *grpc.Server, srv SingleCrawlerServer) {
	s.RegisterService(&_SingleCrawler_serviceDesc, srv)
}

func _SingleCrawler_SingleCrawler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SingleCrawlerServer).SingleCrawler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/single_crawler.SingleCrawler/SingleCrawler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SingleCrawlerServer).SingleCrawler(ctx, req.(*CrawlerReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SingleCrawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "single_crawler.SingleCrawler",
	HandlerType: (*SingleCrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SingleCrawler",
			Handler:    _SingleCrawler_SingleCrawler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "single_crawler.proto",
}
